# Generated by Django 3.0 on 2020-10-15 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_propiedad', models.IntegerField(unique=True)),
                ('mts', models.CharField(max_length=20)),
                ('mts_semicubiertos', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField()),
                ('cant_ambientes', models.IntegerField()),
                ('cochera', models.BooleanField()),
                ('capacidad_cochera', models.IntegerField(blank=True)),
                ('cant_banios', models.IntegerField()),
                ('permite_cancelacion', models.BooleanField()),
                ('tipo_alquiler', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=7)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadCasa',
            fields=[
                ('propiedad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propiedad.Propiedad')),
                ('tipo_propiedad', models.CharField(default='casa', max_length=5)),
                ('patio', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('pileta', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('terraza', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
            ],
            bases=('propiedad.propiedad',),
        ),
        migrations.CreateModel(
            name='PropiedadDepto',
            fields=[
                ('propiedad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propiedad.Propiedad')),
                ('tipo_propiedad', models.CharField(default='departamento', max_length=12)),
                ('frente', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('contrafrente', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('espacios_comunes', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
            ],
            bases=('propiedad.propiedad',),
        ),
        migrations.CreateModel(
            name='PropiedadHabitacion',
            fields=[
                ('propiedad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propiedad.Propiedad')),
                ('tipo_propiedad', models.CharField(default='habitacion', max_length=10)),
                ('banio_individual', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
            ],
            bases=('propiedad.propiedad',),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_zona', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('desc_zona', models.CharField(choices=[('norte', 'Norte'), ('sur', 'Sur'), ('este', 'Este'), ('oeste', 'Oeste')], max_length=20)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='PropietarioPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escritura', models.CharField(max_length=300)),
                ('autorizacion_poder', models.CharField(max_length=150)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedad.Propiedad')),
                ('propietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_oferta', models.CharField(max_length=5, unique=True)),
                ('permite_cancelacion', models.BooleanField()),
                ('periodo_vigencia', models.CharField(max_length=5)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedad.Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='InquilinoPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_alquiler', models.CharField(max_length=10)),
                ('cant_personas', models.IntegerField()),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_senia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inquilino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
                ('propiedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedad.Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_estado', models.CharField(max_length=15)),
                ('propiedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedad.Propiedad')),
            ],
        ),
    ]
