# Generated by Django 3.1.2 on 2020-10-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='cod_propiedad',
        ),
    ]
