# Generated by Django 3.0 on 2020-10-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0002_remove_propiedad_cod_propiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadcasa',
            name='tipo_propiedad',
            field=models.CharField(default='casa', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='propiedaddepto',
            name='tipo_propiedad',
            field=models.CharField(default='departamento', editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='propiedadhabitacion',
            name='tipo_propiedad',
            field=models.CharField(default='habitacion', editable=False, max_length=10),
        ),
    ]
