# Generated by Django 3.0 on 2020-10-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0003_auto_20201028_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='desc_prop',
            field=models.TextField(default='descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedad'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='precio',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
