# Generated by Django 3.1.2 on 2020-10-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0005_auto_20201029_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='tipo_propiedad',
        ),
        migrations.AddField(
            model_name='propiedadcasa',
            name='tipo_propiedad',
            field=models.CharField(default='casa', editable=False, max_length=15),
        ),
    ]
