# Generated by Django 3.1.2 on 2020-10-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0006_auto_20201029_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedaddepto',
            name='tipo_propiedad',
            field=models.CharField(default='departamento', editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='propiedadhabitacion',
            name='tipo_propiedad',
            field=models.CharField(default='habitacion', editable=False, max_length=15),
        ),
    ]
