# Generated by Django 3.1.2 on 2020-10-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0007_auto_20201029_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedadcasa',
            name='tipo_propiedad',
        ),
        migrations.RemoveField(
            model_name='propiedaddepto',
            name='tipo_propiedad',
        ),
        migrations.RemoveField(
            model_name='propiedadhabitacion',
            name='tipo_propiedad',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.CharField(default='default', max_length=15),
            preserve_default=False,
        ),
    ]
