# Generated by Django 3.1.2 on 2020-10-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0008_auto_20201029_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='propiedad',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(choices=[('ocupado', 'Ocupado'), ('disponible', 'Disponible'), ('en mantenimiento', 'En Mantenimiento')], default='disponible', max_length=16),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='zona',
            field=models.CharField(choices=[('norte', 'Norte'), ('sur', 'Sur'), ('este', 'Este'), ('oeste', 'Oeste')], default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EstadoPropiedad',
        ),
        migrations.DeleteModel(
            name='Zona',
        ),
    ]
