# Generated by Django 3.1.2 on 2020-10-31 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0009_auto_20201030_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='periodo_vigencia',
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='mts_semicubiertos',
            field=models.CharField(max_length=10),
        ),
    ]
