# Generated by Django 3.0 on 2020-11-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0009_auto_20201030_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='mts_semicubiertos',
            field=models.CharField(max_length=10),
        ),
    ]
