# Generated by Django 3.1.2 on 2020-10-31 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0010_auto_20201031_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietariopropiedad',
            name='propiedad',
        ),
        migrations.RemoveField(
            model_name='propietariopropiedad',
            name='propietario',
        ),
        migrations.DeleteModel(
            name='InquilinoPropiedad',
        ),
        migrations.DeleteModel(
            name='PropietarioPropiedad',
        ),
    ]
