# Generated by Django 3.1.2 on 2020-11-12 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0012_auto_20201101_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='estado',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='estado_actual',
            field=models.CharField(choices=[('OCUPADO', 'Ocupado'), ('DISPONIBLE', 'Disponible'), ('EN MANTENIMIENTO', 'En Mantenimiento')], default='disponible', max_length=16),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_alquiler',
            field=models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], max_length=7),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='zona',
            field=models.CharField(choices=[('NORTE', 'Norte'), ('SUR', 'Sur'), ('ESTE', 'Este'), ('OESTE', 'Oeste')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propiedadcasa',
            name='patio',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='propiedadcasa',
            name='pileta',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='propiedadcasa',
            name='terraza',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='propiedaddepto',
            name='contrafrente',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='propiedaddepto',
            name='espacios_comunes',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='propiedaddepto',
            name='frente',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='propiedadhabitacion',
            name='banio_individual',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_inicio', models.DateField(auto_now_add=True)),
                ('fec_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('band', models.BooleanField()),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
            ],
        ),
    ]
