# Generated by Django 3.0 on 2020-11-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0013_auto_20201112_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltrarPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(blank=True, choices=[('OCUPADO', 'Ocupado'), ('DISPONIBLE', 'Disponible'), ('EN MANTENIMIENTO', 'En Mantenimiento')], max_length=20, null=True)),
                ('tipo_propiedad', models.CharField(blank=True, choices=[('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento'), ('HABITACION', 'Habitacion')], max_length=15, null=True)),
                ('zona', models.CharField(blank=True, choices=[('NORTE', 'Norte'), ('SUR', 'Sur'), ('ESTE', 'Este'), ('OESTE', 'Oeste')], max_length=10, null=True)),
            ],
        ),
    ]
