# Generated by Django 3.1.2 on 2020-11-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0014_filtrarpropiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtrarpropiedad',
            name='condicion',
            field=models.CharField(blank=True, choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('EN MANTENIMIENTO', 'En Mantenimiento')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado_actual',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('EN MANTENIMIENTO', 'En Mantenimiento')], default='disponible', max_length=16),
        ),
    ]
