# Generated by Django 3.1.2 on 2020-10-31 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0004_auto_20201027_1236'),
        ('propiedad', '0011_auto_20201031_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropietarioPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escritura', models.CharField(max_length=300)),
                ('autorizacion_poder', models.CharField(max_length=150)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
                ('propietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
        ),
        migrations.CreateModel(
            name='InquilinoPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_alquiler', models.CharField(max_length=10)),
                ('cant_personas', models.IntegerField()),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_senia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inquilino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('propiedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
            ],
        ),
    ]
