# Generated by Django 3.0 on 2020-11-12 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20201112_1212'),
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietariopropiedad',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
    ]
