# Generated by Django 3.1.2 on 2020-11-13 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_auto_20201112_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilinopropiedad',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
