# Generated by Django 3.1.2 on 2020-11-13 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20201112_1212'),
        ('contrato', '0003_inquilinopropiedad_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilinopropiedad',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
    ]
