# Generated by Django 3.1.2 on 2020-11-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0004_auto_20201113_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilinopropiedad',
            name='vigencia_alquiler',
            field=models.DateField(),
        ),
    ]
