# Generated by Django 3.1.2 on 2020-11-18 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0005_auto_20201113_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquilinopropiedad',
            old_name='vigencia_alquiler',
            new_name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='inquilinopropiedad',
            name='importe_senia',
        ),
        migrations.AddField(
            model_name='inquilinopropiedad',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquilinopropiedad',
            name='cant_personas',
            field=models.IntegerField(max_length=2),
        ),
    ]
