# Generated by Django 3.1.2 on 2020-11-18 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0006_auto_20201118_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietariopropiedad',
            name='autorizacion_poder',
        ),
        migrations.RemoveField(
            model_name='propietariopropiedad',
            name='escritura',
        ),
        migrations.AddField(
            model_name='propietariopropiedad',
            name='comision',
            field=models.CharField(choices=[('5', '5%'), ('10', '10%'), ('15', '15%'), ('20', '20%'), ('25', '25%'), ('30', '30%')], default='5', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietariopropiedad',
            name='condiciones',
            field=models.TextField(default='Condiciones del contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietariopropiedad',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietariopropiedad',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquilinopropiedad',
            name='cant_personas',
            field=models.IntegerField(),
        ),
    ]
