# Generated by Django 3.0 on 2020-10-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_estado', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_propiedad', models.DecimalField(decimal_places=1, max_digits=2, unique=True)),
                ('tipo_propiedad', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('habitacion', 'Habitacion')], max_length=12)),
                ('descrip_prop', models.CharField(max_length=100)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('mts', models.CharField(max_length=5)),
                ('mts_semicubiertos', models.CharField(max_length=5)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=2)),
                ('cant_ambientes', models.DecimalField(decimal_places=2, max_digits=2)),
                ('cochera', models.BooleanField()),
                ('capacidad_cochera', models.DecimalField(blank=True, decimal_places=2, max_digits=2)),
                ('cant_banios', models.DecimalField(decimal_places=2, max_digits=2)),
                ('permite_cancelacion', models.BooleanField()),
                ('tipo_alquiler', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='PropietarioPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('escritura', models.CharField(max_length=300)),
                ('autorizacion_poder', models.CharField(max_length=150)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.Propiedad')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadZona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_zona', models.DecimalField(decimal_places=1, max_digits=1, unique=True)),
                ('desc_zona', models.CharField(max_length=10)),
                ('prop_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadOferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_oferta', models.DecimalField(decimal_places=1, max_digits=3, unique=True)),
                ('permite_cancelacion', models.BooleanField()),
                ('periodo_vigencia', models.CharField(max_length=5)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('prop_oferta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedad.EstadoPropiedad')),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banio_individual', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('prop_hab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedad.Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadDepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frente', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('contrafrente', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('espacios_comunes', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('prop_depto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedad.Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadCasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patio', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('pileta', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('terraza', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('prop_casa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedad.Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='InquilinoPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_alquiler', models.CharField(max_length=10)),
                ('cant_personas', models.DecimalField(decimal_places=1, max_digits=2)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('importe_senia', models.DecimalField(decimal_places=2, max_digits=3)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.Propiedad')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='estadopropiedad',
            name='estado_propiedad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedad.Propiedad'),
        ),
    ]
