# Generated by Django 3.0 on 2020-10-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquilinopropiedad',
            old_name='propietario',
            new_name='inquilino',
        ),
    ]
