# Generated by Django 3.0 on 2020-10-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0002_auto_20201009_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilinopropiedad',
            name='cant_personas',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='cant_ambientes',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='capacidad',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='capacidad_cochera',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='cod_propiedad',
            field=models.DecimalField(decimal_places=0, max_digits=2, unique=True),
        ),
        migrations.AlterField(
            model_name='propiedadoferta',
            name='cod_oferta',
            field=models.DecimalField(decimal_places=0, max_digits=3, unique=True),
        ),
        migrations.AlterField(
            model_name='propiedadzona',
            name='cod_zona',
            field=models.DecimalField(decimal_places=0, max_digits=1, unique=True),
        ),
    ]
