# Generated by Django 3.0 on 2020-10-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0003_auto_20201009_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='cod_propiedad',
            field=models.DecimalField(decimal_places=0, max_digits=6, unique=True),
        ),
    ]
