# Generated by Django 3.0 on 2020-10-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0004_auto_20201009_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='cant_banios',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
