# Generated by Django 3.0 on 2020-10-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0005_auto_20201009_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='mts',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='mts_semicubiertos',
            field=models.CharField(max_length=20),
        ),
    ]
