# Generated by Django 3.0 on 2020-10-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0006_auto_20201009_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadzona',
            name='cod_zona',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
