# Generated by Django 3.1.2 on 2020-10-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_remove_persona_cod_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='mail',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.BigIntegerField(max_length=13),
        ),
        migrations.AlterField(
            model_name='personafisica',
            name='cuil',
            field=models.BigIntegerField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='cuit',
            field=models.BigIntegerField(max_length=11, unique=True),
        ),
    ]
