# Generated by Django 3.1.2 on 2020-10-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20201027_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='personafisica',
            name='cuil',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='cuit',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
