# Generated by Django 3.1.2 on 2020-11-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20201027_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personafisica',
            old_name='nombre_apellido',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='personafisica',
            name='apellido',
            field=models.CharField(default='default', max_length=40),
        ),
    ]
