# Generated by Django 3.1.2 on 2020-11-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20201112_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='mail',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='personafisica',
            name='apellido',
            field=models.CharField(max_length=40),
        ),
    ]
