# Generated by Django 3.1.2 on 2020-11-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_auto_20201113_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personafisica',
            name='desc_per',
        ),
        migrations.RemoveField(
            model_name='personajuridica',
            name='desc_per',
        ),
        migrations.AddField(
            model_name='persona',
            name='desc_per',
            field=models.CharField(default='DEFAULT', max_length=8),
            preserve_default=False,
        ),
    ]
