# Generated by Django 3.0 on 2020-10-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cod_persona',
            field=models.DecimalField(decimal_places=0, max_digits=2, unique=True),
        ),
    ]
