# Generated by Django 3.0 on 2020-10-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20201009_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tipo_persona',
        ),
        migrations.AddField(
            model_name='personafisica',
            name='desc_per',
            field=models.CharField(default='fisica', max_length=6),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='desc_per',
            field=models.CharField(default='juridica', max_length=8),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cod_persona',
            field=models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
